[workspace]
members = [
    "crates/mkt",
    "crates/mkt-core",
    "crates/mkt-types",
    "crates/exchanges/binance",
    "crates/exchanges/bitget",
    "crates/exchanges/bybit",
    "crates/exchanges/mexc",
    "crates/exchanges/okx",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.86"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pluveto/mkt"

[workspace.dependencies]
anyhow = "=1.0.102"
async-trait = "=0.1.89"
binance-sdk = { version = "=49.0.0", default-features = false, features = ["rustls-tls", "spot", "derivatives_trading_usds_futures"] }
derive_builder = "=0.10.2"
mkt-core = { path = "crates/mkt-core", version = "0.1.0" }
mkt-exchange-binance = { path = "crates/exchanges/binance", version = "0.1.0" }
mkt-exchange-bitget = { path = "crates/exchanges/bitget", version = "0.1.0" }
mkt-exchange-bybit = { path = "crates/exchanges/bybit", version = "0.1.0" }
mkt-exchange-mexc = { path = "crates/exchanges/mexc", version = "0.1.0" }
mkt-exchange-okx = { path = "crates/exchanges/okx", version = "0.1.0" }
mkt-types = { path = "crates/mkt-types", version = "0.1.0" }
reqwest = { version = "=0.12.24", default-features = false, features = ["rustls-tls"] }
rust_decimal = { version = "=1.42.0", default-features = false }
secrecy = { version = "=0.10.3" }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = { version = "=1.0.149" }
time = { version = "=0.3.45", default-features = false, features = ["std", "serde"] }
strum = "=0.28.0"
strum_macros = "=0.28.0"
thiserror = "=2.0.18"
tokio = { version = "=1.52.3", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-tungstenite = { version = "=0.26.2", default-features = false, features = ["rustls-tls-webpki-roots"] }
url = "=2.5.8"

[workspace.metadata.release-plz]
release = true
