[workspace]
changelog_update = true
changelog_path = "./CHANGELOG.md"
publish = true
dependencies_update = true
semver_check = true
release_always = false

[[package]]
name = "mkt-types"

[[package]]
name = "mkt-core"
dependencies = ["mkt-types"]

[[package]]
name = "mkt"
dependencies = ["mkt-core", "mkt-types"]
