[package]
name = "mkt-core"
description = "Core traits, errors, and configuration for the mkt exchange client ecosystem."
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = true
categories = ["finance"]
keywords = ["crypto", "exchange", "trading", "core"]

[dependencies]
async-trait.workspace = true
derive_builder.workspace = true
mkt-types.workspace = true
secrecy.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true

[dev-dependencies]
time.workspace = true
tokio.workspace = true
