[package]
name = "mkt-exchange-okx"
description = "OKX adapter for mkt."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = true

[dependencies]
mkt-core.workspace = true
mkt-types.workspace = true
reqwest.workspace = true
url.workspace = true
