[package]
name = "mkt-types"
description = "Stable business data types for the mkt exchange client ecosystem."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = true

[features]
default = []
serde = ["dep:serde", "rust_decimal/serde", "time/serde"]

[dependencies]
derive_builder.workspace = true
rust_decimal.workspace = true
serde = { workspace = true, optional = true }
serde_json.workspace = true
time.workspace = true
strum.workspace = true
strum_macros.workspace = true
