[package]
name = "mkt-exchange-bybit"
description = "Bybit adapter for mkt."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
mkt-core.workspace = true
mkt-types.workspace = true
reqwest.workspace = true
tokio-tungstenite.workspace = true
url.workspace = true
