[package]
name = "mkt-exchange-mexc"
description = "MEXC adapter for mkt."
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = true
categories = ["finance"]
keywords = ["crypto", "exchange", "trading", "mexc"]

[dependencies]
async-trait.workspace = true
futures-util = "=0.3.31"
mkt-core.workspace = true
mkt-exchange-common.workspace = true
mkt-types.workspace = true
prost = "=0.13.5"
reqwest.workspace = true
rust_decimal.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tokio-tungstenite = { workspace = true, features = ["connect"] }
url.workspace = true
