[package]
name = "mkt-exchange-mexc"
description = "MEXC adapter for mkt."
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = true
categories = ["finance"]
keywords = ["crypto", "exchange", "trading", "mexc"]

[dependencies]
mkt-core.workspace = true
mkt-types.workspace = true
reqwest.workspace = true
url.workspace = true
